### ISSUE TITLE
"Could not load log entries"

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/logreader#1058]
### Steps to reproduce
1. ???

### Expected behaviour

I can read the logs

### Actual behaviour

I get an error toast with "Could not load log entries"

![Bildschirmfoto vom 2023-11-24 11-49-40](https://github.com/nextcloud/logreader/assets/1374172/08128154-6067-4519-841b-916896253839)

The browser network logs shows that the request for logs errors with HTTP500.

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 28.0.0 RC1

**Where did you install Nextcloud from:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by susnux** [comment]
> The browser network logs shows that the request for logs errors with HTTP500.

Is there any message in the response body of the failing request? Or could you have a look at the logfile manually?
I can not reproduce this, neither with a local dev setup nor on tech preview.

**Comment by ChristophWurst** [comment]
It's empty

![image](https://github.com/nextcloud/logreader/assets/1374172/0fd340dc-05f4-4586-9051-d50f97396eef)

**Comment by ChristophWurst** [comment]
OOOOOOF

> blocked by uBlock origin

**Comment by BrianBlaze** [comment]
Just updated from the latest 27 version to 28.0.

I have a similar/same issue. On my admin overview it says: 33 errors in the logs since December 5, 2023.

Checking the logging tab I have the same result : "Could not load log enteries"

Checking my log manually I see this in my logs: https://github.com/nextcloud/photos/issues/2187

I am not sure if it's connected, and not sure what other info I can give to help push this along, but I thought more input is better than less :)

**Comment by susnux** [comment]
@BrianBlaze Could you check that if you use an adblocker that it does not block that request? Otherwise disable it and report that false positive to your adblocker.

**Comment by BrianBlaze** [comment]
> @BrianBlaze Could you check that if you use an adblocker that it does not block that request? Otherwise disable it and report that false positive to your adblocker.

100% an adblock thing! Thank you for such a quick response :)

**Comment by drifter75** [comment]
Just deployed version 28.0 and got this error.... but wait for few seconds the logs will be shown without disabling uBlock. With uBlock for site disabled it appeared without any delay.

**Comment by susnux** [comment]
> but wait for few seconds the logs will be shown without disabling uBlock. With uBlock for site disabled it appeared without any delay.

Yes as said above uBlock uses a block list from AdblockPlus that has a false positive on the logging API... So the initial loading of log entries will fail and only if polling is enabled it will work later.

So I recommend you to disable your adblocker on your Nextcloud instance and report this to your adblocker issue tracker to get the entry out of the list.

**Comment by proninyaroslav** [comment]
Same problem with uBlock Lite.

**Comment by Henk57** [comment]
Same problem with Ghostery.

**Comment by furai** [comment]
https://github.com/easylist/easylist/blob/af99b850d37219eac88e33c4e4d80f1643bf9e9b/easyprivacy/easyprivacy_general.txt#L305

This is actually caused by this entry in easylist. It's been there for 7 years so I don't think it's going anywhere. Only thing one can probably do is to just add the sites to whitelist or not use easylist but that's probably out of question. :)

**Comment by magikmw** [comment]
> So I recommend you to disable your adblocker on your Nextcloud instance and report this to your adblocker issue tracker to get the entry out of the list.

> This is actually caused by this entry in easylist. It's been there for 7 years so I don't think it's going anywhere. Only thing one can probably do is to just add the sites to whitelist or not use easylist but that's probably out of question. :)

I would like to ask maintainers to reopen this issue in light of above.
  
While correcting due to user's particular adblocking issues is not a common theme among any open source developement, I would postulate we can avoid the whole issue by changing the URL that gets caught by the adblocker to something that doesn't.

For example, while `/api/log?` appears in the mentioned filter list, `/api/logs` doesn't.

If I understand correctly, this change would actually need to happen first on the nextcloud/server project's side.

This is especially important in larger instances in organizations that allow use of adblockers, but don't enforce rules on users beyond defaults. I was certain it was an error in Nextcloud itself or my particular deployment.

**Comment by susnux** [comment]
It does not look like too many users are affected by this, otherwise there would be already a bug report for easylist for blocking a that generic item.

Feel free to open an issue at easylist so they can fix it - or create a PR for adjusting the API endpoint here :)

**Comment by joshtrichards** [comment]
Hi @magikmw Also, there's already a dedicated Issue for tracking this possibility here so no need to fill this closed issue with further discussion that'll get overlooked/lost. Instead use #1136
