### ISSUE TITLE
Setup check fails while it should skip non-`file` `log_type`s

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/logreader#1448]
![Image](https://github.com/user-attachments/assets/924befd7-8f66-4195-b36c-0c338d7b6836)
The setup check fails, but there actually isn't anything wrong. The logs can't be read because they are not in a file, but that is expected.
At most this should show a warning/info that the logs can't be checked for errors.

**Comment by joshtrichards** [comment]
I guess the question is do we:

- (a) handle this like we currently are and consider it an error if the logreader app is enabled, but a non-file log_type is configured?
- (b) handle it like we are currently, but generate a less prominent (info level) message?
- (c) return nothing / go silent if the log_type isn't file?

I tend to agree that (b) or maybe even (c) makes sense.

I lean towards (c). Particularly since we already indicate (when trying to view the log) if the log_type isn't supported by logreader. This avoids generating a warning or info message on the setup check for an otherwise valid configuration.

**Comment by provokateurin** [comment]
The logreader app is shipped and enabled by default, so (a) is not really an option to handle this as every will see this "error":
https://github.com/nextcloud/server/blob/407ac7f739a7cb2136fa717b06c9163b05f36def/core/shipped.json#L25
https://github.com/nextcloud/server/blob/407ac7f739a7cb2136fa717b06c9163b05f36def/core/shipped.json#L75

**Comment by provokateurin** [comment]
@Antreesy @icewind1991 what do you think?

**Comment by Antreesy** [comment]
I'd say it should be (b) if logreader is enabled and (c) otherwise. That way we'll indicate that logreader can't be used with selected log_type

**Comment by provokateurin** [comment]
If the app is not enabled there will also be no error in the setup check
