### ISSUE TITLE
Missing ":"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/logreader#264]
Missing ":" in time zone:
![obraz](https://user-images.githubusercontent.com/47037905/66125071-56064100-e5e6-11e9-86a6-2047dbbde287.png)
Correctly it should be: +02:00

App:
Nextcloud 17.0.0
Log Reader 2.2.0

**Comment by joshtrichards** [comment]
We seem to be set-up to be doing this. I think it's an accident it's not displaying like that.

The backend already uses the PHP ATOM style formatting (https://www.php.net/manual/en/class.datetime.php) by default: `"Y-m-d\\TH:i:sP"` and that's what we stash in the raw log file. Unfortunately, it looks like we still have [an older?] default format defined in the frontend: `"Y-m-d\\TH:i:sO"` still:

https://github.com/nextcloud/logreader/blob/827855fd462482b1cd98407abd57cce005eb1a86/src/App.js#LL17C6-L17C6

As a workaround the following will work at an installation level in the config.php since the frontend will accept its default being overridden:

`'logdateformat' => 'Y-m-d\\TH:i:sP',`

I think the permanent solution is to change earlier mentioned line to: `"Y-m-d\\TH:i:sP"` since it was an oversight (well either that or have the frontend pull its default from the backend so they're always the same... which now that I look at it sort of looks like it should already be happening 🤔 @icewind1991 ?). 

There don't seem to be too many uses for this default in the front-end and it's cosmetic only so seems safe to tweak the default IMO. Particularly given I think it was just an oversight it doesn't match up with the backend.

**Comment by susnux** [comment]
Fixed since Nextcloud 28, ref: https://github.com/nextcloud/logreader/pull/936
