### ISSUE TITLE
occ command / logging command needs to be documented

### ISSUE THREAD

**Issue by KB7777** [nextcloud/logreader#421]
```
log
 log:manage     manage logging configuration
 **log:owncloud**   manipulate Nextcloud logging backend

```
and others here -- https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/occ_command.rst#id31

**Comment by wiswedel** [comment]
server's core commands are documented under https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#logging-commands.

This app brings two more:

```
log:tail    Tail the nextcloud logfile
log:watch   Watch the nextcloud logfile
```

Since this app is virtually a core app, they should be documented in the server's core documentation as well (maybe with a hint that those two require this app being enabled)
